{
 "title": "HTTP Server Projeto Korp",
 "tags": [
  "go",
  "prometheus",
  "korp"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Disponibilidade do serviço",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "korp_service_up", "legendFormat": "Disponibilidade" }
   ]
  },
  {
   "title": "Volume de requisições",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(korp_requests_total[1m])", "legendFormat": "Requisições por segundo" }
   ]
  },
  {
   "title": "Total acumulado de requisições",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "korp_requests_total", "legendFormat": "Total acumulado" }
   ]
  },
  {
   "title": "Latência p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(korp_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p95"
    }
   ]
  }
 ]
}